spec:
  name: portfolio
  static_sites:
    - environment_slug: html
      name: portfolio-website
      github:
        repo: Dennis-Krasnov/Portfolio
        branch: master
        deploy_on_push: false
      build_command: npm run build
      output_dir: build