name: Continuous Deployment

on:
  push:
    tags:
      - deploy

env:
  OCI_IMAGE_PATH: /tmp/portfolio-web

jobs:
  push:
    needs: [smoke-test, check-vulnerability]
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: registry.digitalocean.com/krasnov/portfolio-web
      IMAGE_TAG: ${{ github.sha }}
    steps:
#      - name: Download local OCI image
#        uses: actions/download-artifact@v2
#        with:
#          name: portfolio-web-image
#
#      - name: Restore local OCI image
#        run: buildah pull oci:$OCI_IMAGE_PATH
#
#      - name: Rename image
#        run: buildah tag localhost$OCI_IMAGE_PATH $IMAGE_NAME:$IMAGE_TAG

      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Build OCI image
#        run: buildah unshare ./scripts/build-container.sh
#
#      - name: Install doctl
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#
#      - name: Log in to DigitalOcean Container Registry with short-lived credentials
#        run: doctl registry login --expiry-seconds 600
#
#      - name: Push OCI image to DigitalOcean Container Registry
#        run: buildah push portfolio-web $IMAGE_NAME:$IMAGE_TAG

    deploy:
      needs: push
      runs-on: ubuntu-latest
      steps:
        - name: Hello
          run: echo hello