name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OCI_IMAGE_PATH: /tmp/portfolio-web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build OCI image
      run: buildah unshare ./scripts/build-container.sh

    - name: Archive local OCI iamge
      run: buildah push portfolio-web oci:$OCI_IMAGE_PATH:portfolio-web

    - name: Upload local OCI image
      uses: actions/upload-artifact@v2
      with:
        name: portfolio-web-image
        path: $OCI_IMAGE_PATH

  smoke-test:
    needs: build
    runs-on: ubuntu-latest
    env:
      PORT: 8080
    steps:
      - name: Download local OCI image
        uses: actions/download-artifact@v2
        with:
          name: portfolio-web-image

      - name: Restore local OCI image
        run: buildah pull oci:$OCI_IMAGE_PATH

      - name: Smoke test
        run: |
          podman run --rm -d -p $PORT:80 portfolio-web
          sleep 1
          python scripts/smoke-test.py

  check-vulnerability:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo hello

      # TODO: https://github.com/aquasecurity/trivy-action