name: Continuous Integration and Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build web bundle
      run: npm ci

    - name: Download npm dependencies
      run: npm run build

    - name: Upload web bundle
      uses: actions/upload-artifact@v2
      with:
        name: portfolio-web-bundle
        path: build

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to digital ocean app platform
        uses: digitalocean/app_action@main
        with:
          app_name: my_DO_app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}