name: Build and Deploy CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Install npm dependencies
      run: npm install
      
    - name: Build Svelte project
      run: npm run build
      
    - name: Upload public folder
      uses: actions/upload-artifact@v2
      with:
        name: public-folder
        path: public/

  # TODO: generate resume job, redeploy public folder (parallel with profile)!

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download public folder
        uses: actions/download-artifact@v2
        with:
          name: public-folder
          path: public
    
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  profile:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://krasnov-dev.web.app/
            https://krasnov-dev.web.app/resume
            https://krasnov-dev.web.app/projects/nanobox
            https://krasnov-dev.web.app/projects/diet-driven
            https://krasnov-dev.web.app/projects/portfolio
            https://krasnov-dev.web.app/projects/chess
          uploadArtifacts: true