name: Build and Deploy CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Install npm dependencies
      run: npm install
      
    - name: Build Svelte project
      run: npm run build

    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1

    - name: Install Gimp
      run: sudo snap install gimp

    - name: Generate project thumbnails
      run: npm run export-project-thumbnails
      
    - name: Upload public folder
      uses: actions/upload-artifact@v2
      with:
        name: public-folder
        path: public/

  deploy-hosting:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download public folder
        uses: actions/download-artifact@v2
        with:
          name: public-folder
          path: public

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-functions:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install npm dependencies
        run: |
          cd functions
          npm install
      
      - name: Update sendgrid API key
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: functions:config:set sendgrid.api_key="${{ secrets.SENDGRID_API_KEY }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  profile:
    needs: deploy-hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: https://krasnov.dev
          uploadArtifacts: true